services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:18
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: healthcare_email_triage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d healthcare_email_triage" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:




